[pytest]
# Путь к тестам
testpaths = tests

# Параметры запуска по умолчанию
addopts = 
    -v
    --tb=short
    --maxfail=100

# Таймаут для тестов
timeout = 30

# Переменные окружения
env =
    BASE_URL = https://qa-internship.avito.com